---
title: "Zen demo site"
baseURL: "https://zen-demo.xdeb.org/"
theme: "github.com/frjo/hugo-theme-zen/v2"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Fredrik Jonsson"
  url: "https://xdeb.org"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "frjo@xdeb.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo demo site."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  realfavicongenerator: true
  sidebar: true
  submitted: true
